Repository minetoblend/osu-cad, pull requests merged in 2025-05, with the labels that each got.

#101 improve cursortrail rendering
  packages/ruleset-osu/src/ui/OsuCursor.ts
Labels: size/M

#102 Fix autoplay breaking in longer gaps between hitobjects
  packages/ruleset-osu/src/gameplay/OsuAutoPlayController.ts
Labels: size/S

#104 Fix combo colors always being updated
  packages/core/src/rulesets/hitObjects/drawables/DrawableHitObject.ts
Labels: size/XS

#103 Add support for `cursorRotate`
  packages/core/src/skinning/SkinConfiguration.ts
  packages/ruleset-osu/src/ui/OsuCursor.ts
Labels: size/M

#105 Fix follow circles disappearing when skin changes
  packages/ruleset-osu/src/hitObjects/drawables/DrawableSlider.ts
  packages/ruleset-osu/src/hitObjects/drawables/SliderInputManager.ts
  packages/ruleset-osu/src/judgements/OsuJudgementResult.ts
  packages/ruleset-osu/src/judgements/OsuSliderJudgementResult.ts
  packages/ruleset-osu/src/skinning/FollowCircle.ts
Labels: size/M

#106 Fix sliderball not fading in
  packages/ruleset-osu/src/skinning/legacy/LegacySliderBall.ts
Labels: size/XS

#108 Fix slider velocity having wrong precision
  packages/core/src/beatmaps/timing/LegacyTimingPoint.ts
Labels: size/XS

#109 Make gamehost pauseable
  packages/framework/src/platform/GameHost.ts
Labels: size/S
